editorconfig/editorconfig-core-go

editorconfig.go
editorconfig_test.go
testdata/a.ini
testdata/root/src/a.ini

Which is required for core-test.

Add function to specify editorconfig config basename

---

.gitmodules
.travis.yml
Makefile
cmd/editorconfig/main.go
editorconfig.go

- Tests using core-test are disabled for now because it requires many extra fixes (will be done in another PR)

Add cmd/editorconfig

---

cmd/editorconfig/main.go

I'm not sure if this is a good addition but I think it is totally okay to pass relative pathnames.

Make filepath absolute

---

README.md

@andreynering @greut I really really appreciate your work, Thanks!
@andreynering Now is it OK to merge this? Sorry but I could not fully track recent changes, if I'm missing something please tell.
Reverts #13 
See #12

Comment-in travis badge and remove "not recommended" message

---

cmd/editorconfig/main.go

release: prepare v1.3.1

---

Makefile

core-test: run 182 of 193 tests

---

.travis.yml

travis: bump go and travis

---

Makefile
cmd/editorconfig/main.go
editorconfig.go
go.mod
go.sum

One more test passing which required quite some refactoring to pass the version around.

implement 0.9.0 behavior

---

editorconfig.go
editorconfig_test.go

Back in #19, I've changed some test assertions on the Go side which were correct. This addresses that issue...

Definition: fix values inheritance

---

.travis.yml
Makefile
editorconfig.go

- use core-test master
- pass the `root_file_mixed_case` test

Bump core test

---

CHANGELOG.md
cmd/editorconfig/main.go

prepare release v2.2.2

---

.golangci.yml
.travis.yml
Makefile
cmd/editorconfig/main.go
editorconfig.go
editorconfig_test.go
fnmatch.go
fnmatch_test.go

An attempt to improve the overall quality by adding a bunch of linters and static analysis.

travis: run golangci-lint

---

CHANGELOG.md
cmd/editorconfig/main.go

Bump the minor version to reflect the new features.

changelog: prepare release

---

.golangci.yml
cached_parser.go
cmd/editorconfig/main.go
config.go
definition.go
editorconfig.go
editorconfig_test.go
fnmatch.go
fnmatch_test.go

whitespaces are precious, we could use more of them.

lint: put more whitespaces

---

go.mod
go.sum

https://github.com/go-ini/ini/releases/tag/v1.54.0

dep: go-ini v1.54.0

---

CHANGELOG.md
cmd/editorconfig/main.go

update the changelog and bump the version.

prepare release

---

.travis.yml

also bumping cmake and golangci-lint

travis: build on go 1.14

---

.github/actions/go-test/Dockerfile
.github/actions/go-test/action.yml
.github/workflows/main.yml

ci: update action versions

---

.gitignore
.goreleaser.yml
Dockerfile
Makefile
cmd/editorconfig/main.go

[goreleaser](https://goreleaser.com/) is a fantastic tool to package go programs. Let's use it.

goreleaser: use it

---

README.md
definition.go
go.mod

definition: wrap errors

---

.github/actions/golangci-lint/Dockerfile
.github/actions/golangci-lint/action.yml
.github/workflows/golangci-lint.yml
.github/workflows/main.yml

https://github.com/marketplace/actions/run-golangci-lint

ci: use official golangci-lint action

---

go.mod
go.sum

https://github.com/go-ini/ini/releases/tag/v1.60.1

upgrade:go-ini v1.60.1

---

CHANGELOG.md

changelog: ++

---

editorconfig_test.go

test: more test

---

go.mod
go.sum

:package: https://github.com/go-ini/ini/releases/tag/v1.61.0

chore: go-ini v1.61.0

---

.github/workflows/golangci-lint.yml
go.mod
go.sum

https://github.com/google/go-cmp/releases/tag/v0.5.3

chore: bump google/go-cmp

---

editorconfig.go
fnmatch.go

fix: path on windows

---

go.mod
go.sum

Bump x/mod library

---

.github/workflows/golangci-lint.yml
.golangci.yml
cached_parser.go
cmd/editorconfig/main.go
config.go
definition.go
editorconfig.go
editorconfig_test.go
fnmatch.go
fnmatch_test.go
internal/assert/assert.go
simple_parser.go

feat: bump and activate more linters

---

.editorconfig
go.mod
go.sum

time for dependabot integration it seems

chore: Bump golang.org/x/mod

---

.github/dependabot.yml
.github/workflows/golangci-lint.yml
.github/workflows/main.yml

chore: bump some versions

---

CHANGELOG.md

it's passing new tests, let's bump the minor version.

changelog: 2.4.0

---

config.go
go.sum

newly released and already bugged on Go 1.16 :)
https://gitlab.com/greut/eclint/-/jobs/1047782649

fix: IsNotExist fails with the wrapping

---

CHANGELOG.md

prepare v2.4.1

---

.github/workflows/golangci-lint.yml
.golangci.yml
definition.go
fnmatch.go

feat: bump golangci-lint from 1.36 to 1.37

---

CHANGELOG.md

prepare v2.4.2

---

.github/workflows/golangci-lint.yml
.github/workflows/main.yml
.golangci.yml
editorconfig.go
editorconfig_test.go

chore: bump golangci-lint and fixes

---

.github/dependabot.yml
.github/workflows/golangci-lint.yml
.golangci.yml
fnmatch.go

feat: bump golangci-lint from 1.43 to 1.44

---

.github/workflows/golangci-lint.yml
.github/workflows/main.yml
.golangci.yml
CHANGELOG.md
go.mod
go.sum

prepare v2.4.5

---

README.md

fix: badge pointing to pkg.go.dev

---

.github/workflows/semgrep.yml

Safer code with better checks.

feat: enable semgrep checks

---

.github/workflows/golangci-lint.yml
.golangci.yml
cmd/editorconfig/main.go
config.go
definition.go
editorconfig_test.go
fnmatch.go
fnmatch_test.go
simple_parser.go

fix: golangci-lint warnings

---

README.md
cached_parser.go
cmd/editorconfig/main.go
config.go
definition.go
editorconfig.go
editorconfig_test.go
go.mod
go.sum
parser.go
simple_parser.go
testdata/a.ini

feat: graceful parser

---

.github/workflows/golangci-lint.yml

fix(ci): bump golangci-lint from 1.49 to 1.52

---

editorconfig.go
fnmatch.go

Should fix #168 as the tests are now passing there.

fix: path matches on Windows

---

.github/workflows/golangci-lint.yml
fnmatch.go
fnmatch_test.go

https://github.com/golangci/golangci-lint/releases/tag/v1.56.0

chore: bump golanci-lint from 1.54 to 1.56

---

config.go

that will help with https://github.com/editorconfig-checker/editorconfig-checker/issues/330

fix: Windows path overrides are broken

---

.github/workflows/golangci-lint.yml
.golangci.yml

chore(ci): bump golangci-lint to 1.64
