.travis.yml
CMakeLists.txt
Makefile
README.md
cmd/editorconfig/main.go
editorconfig.go
editorconfig_test.go
fnmatch.go
fnmatch_test.go

- the fnmatch is somewhat stolen from [editorconfig-core-py](https://github.com/editorconfig/editorconfig-core-py)
- core-test is bumped to v0.13
- 15 tests are still breaking (any help is welcome)
```
92% tests passed, 15 tests failed out of 193
Total Test time (real) =   0.55 sec
The following tests FAILED:
120 - tab_width_default_ML (Failed)
122 - indent_size_default_ML (Failed)
125 - indent_size_default_with_tab_width_ML (Failed)
126 - lowercase_values1_ML (Failed)
127 - lowercase_values2_ML (Failed)
129 - lowercase_names (Failed)
148 - comments_after_section (Failed)
155 - octothorpe_comments_after_section (Failed)
158 - octothorpe_in_property (Failed)
159 - escaped_octothorpe_in_property (Failed)
163 - max_property_name (Failed)
164 - max_property_value (Failed)
166 - …
```

fnmatch: rewrite

---

editorconfig.go

Now running editorconfig-checker against itself continues to work.

fix editorconfig-checker own check

---

Makefile
editorconfig.go
editorconfig_test.go

Passing more tests don't mean that the features are correct, but it's a starting point.
**before**
```
100% tests passed, 0 tests failed out of 172
```
**now**
```
100% tests passed, 0 tests failed out of 179
```

Unset support

---

editorconfig.go

`GetDefinitionForFilenameWithConfigname`
GoReportCard suggests that: https://goreportcard.com/report/github.com/editorconfig/editorconfig-core-go#golint

docs: Add comment to exported function

---

editorconfig.go

And deprecate ParseBytes, as it's just a single-line func.
Updates #31.

allow parsing from an io.Reader

---

editorconfig.go
editorconfig_test.go

a redo of #32, which had tests and remove some things I consider to be hacks, such as `ioutil.NopCloser(io.Reader)`.

tests for io.reader

---

Makefile
editorconfig.go

Passing three more tests regarding maximum length for section name, properties and values.
> The maximum length of a section name is 4096 characters. All sections exceeding this limit are ignored.
> [...]
> The maximum length of a property name is 50 characters and the maximum length of a property value is 255 characters. Any property beyond these limits would be ignored.
>
> https://editorconfig-specification.readthedocs.io/en/latest/

config: skip lengthy values

---

CHANGELOG.md
cmd/editorconfig/main.go

Let's publish some code. Bumping the minor version as there is the new `Parse` call.

changelog: prepare v2.2.0 release

---

cmd/editorconfig/main.go
editorconfig.go
editorconfig_test.go

A follow up to #31, there is a `Write` accepting the `io.Writer` interface.

ec: implement Write(io.Writer)

---

editorconfig.go

If the .editorconfig file cannot be read for a different reason than
the file does not exist, the error is not dealt with and a panic will
occur.

editorconfig: fix error mangling

---

.golangci.yml
Makefile
cached_parser.go
cmd/editorconfig/main.go
config.go
definition.go
editorconfig.go
parser.go
simple_parser.go

This addresses the #30 issue. It proposes a cache for the `.editorconfig` definition
master branch running on https://github.com/dotnet/roslyn 
```console
$ time editorconfig $(git ls-files) | wc -l
680099
real    0m7.575s
user    0m8.568s
sys     0m0.764s
```
this branch
```console
$ time editorconfig $(git ls-files) | wc -l
680099
real    0m1.862s
user    0m1.912s
sys     0m0.402s
```
Previous discussions were made under #48 - Kudos go to @andreynering for the useful reviews and feedbacks.

cached parser

---

config.go
definition.go
go.mod
go.sum

semver used by go modules is smaller and closer to our needs than the one used so far.

semver: use golang's package

---

go.mod
go.sum

go-ini 1.55.0 supports non-unique section which doesn't change anything for this library.
https://github.com/go-ini/ini/compare/v1.54.0...v1.55.0

go-ini v1.55.0

---

go.mod
go.sum

- https://github.com/google/go-cmp/releases/tag/v0.4.1
- https://github.com/go-ini/ini/releases/tag/v1.56.0

mod: upgrade go-cmp, ini, x/mod

---

go.mod
go.sum

- https://github.com/go-ini/ini/releases/tag/v1.57.0
- https://github.com/google/go-cmp/releases/tag/v0.5.0

dep: bump go-ini, go-cmp

---

go.mod
go.sum

https://github.com/google/go-cmp/releases/tag/v0.5.1

feat: bump go-cmp

---

go.mod
go.sum

https://github.com/go-ini/ini/releases/tag/v1.58.0

bump: go-ini

---

go.mod
go.sum

- https://github.com/google/go-cmp/releases/tag/v0.5.2
- https://github.com/go-ini/ini/releases/tag/v1.60.2

deps: bump go-cmp, go-ini

---

go.mod
go.sum

https://github.com/go-ini/ini/releases/tag/v1.62.0

chore: go-ini v1.62.0

---

go.mod
go.sum

https://github.com/google/go-cmp/releases/tag/v0.5.4

chore: bump google/go-cmp to v0.5.4

---

CHANGELOG.md

- Fix path separator on Windows
([#83](https://github.com/editorconfig/editorconfig-core-go/pull/89));
- Upgrade go-cmp v0.5.4
([#91](https://github.com/editorconfig/editorconfig-core-go/pull/91)).

changelog: ++

---

.goreleaser.yml

https://goreleaser.com/deprecations#dockerbinaries

fix: goreleaser deprecation

---

Makefile
fnmatch.go
fnmatch_test.go

making the tests added in #93 pass, with some little cheating but that's what you get for going with a regexp-based reference implementation.

feat: pass new test-suite

---

go.mod
go.sum

https://github.com/google/go-cmp/releases/tag/v0.5.6

chore: bump go-cmp from 0.5.5 to 0.5.6

---

.goreleaser.yml
CHANGELOG.md

- Upgrade go-cmp v0.5.6
([#110](https://github.com/editorconfig/editorconfig-core-go/pull/110));
- Upgrade go-ini v1.63.2;
- Upgrade x/mod v0.5.0
([#111](https://github.com/editorconfig/editorconfig-core-go/pull/111));
- Fix problems spotted by golangci-lint
([#115](https://github.com/editorconfig/editorconfig-core-go/pull/115));

prepare v2.4.3

---

.github/workflows/golangci-lint.yml
.golangci.yml
go.mod

Go 1.15 is the last supported one, so bumping make sense as well.

feat: bump golangci-lint from 1.42 to 1.43

---

CHANGELOG.md

241a82b feat: bump golangci-lint from 1.43 to 1.44
9f6d1eb build(deps): bump gopkg.in/ini.v1 from 1.66.3 to 1.66.4 (#124)
64542a4 build(deps): bump gopkg.in/ini.v1 from 1.66.2 to 1.66.3 (#123)
4564d8d build(deps): bump github.com/google/go-cmp from 0.5.6 to 0.5.7 (#122)
1dba889 build(deps): bump gopkg.in/ini.v1 from 1.65.0 to 1.66.2 (#121)
9925b14 build(deps): bump gopkg.in/ini.v1 from 1.64.0 to 1.65.0 (#120)
6c6a3c5 build(deps): bump gopkg.in/ini.v1 from 1.63.2 to 1.64.0 (#119)
a4dd340 feat: bump golangci-lint from 1.42 to 1.43 (#118)
ef4b4a3 build(deps): bump golang.org/x/mod from 0.5.0 to 0.5.1 (#117)

prepare v2.4.4

---

CHANGELOG.md
go.mod

2552daa feat: graceful parser (#144)
8f29b26 build(deps): bump github.com/google/go-cmp from 0.5.8 to 0.5.9 (#143)
43b5f7f fix: golangci-lint warnings (#142)
628ea1d build(deps): bump gopkg.in/ini.v1 from 1.66.6 to 1.67.0 (#141)
560dd96 chore: tests using Go 1.19 (#139)
bdd12ab feat: enable semgrep checks (#138)
5392fc9 fix: badge pointing to pkg.go.dev (#137)

prepare v2.5.0

---

CMakeLists.txt

Those tests are failing locally, maybe things are better here.

chore: bump core-test to latest commit

---

README.md

Some code blocks in README were not sytnax-highlighted, this fixes it.

Enable syntax highlight for README blocks

---

CHANGELOG.md

7354273 fix: path matches on Windows (#170)
de7896a build(deps): bump actions/checkout from 3 to 4 (#169)
0bb51f1 build(deps): bump golangci/golangci-lint-action from 3.6.0 to 3.7.0 (#167)
73c37c4 feat: replace go-multierror with Go 1.20 native joins (#156)
83a3feb chore(ci): bump golangci-lint to 1.53 (#166)
d17d599 build(deps): bump golang.org/x/mod from 0.11.0 to 0.12.0 (#165)
9b237be build(deps): bump golang.org/x/mod from 0.10.0 to 0.11.0 (#163)
c6257d5 build(deps): bump golangci/golangci-lint-action from 3.5.0 to 3.6.0 (#164)
b864fff build(deps): bump golangci/golangci-lint-action from 3.4.0 to 3.5.0 (#162)

prepare v2.6.0

---

editorconfig.go

there is a dash, https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties#charset

fix: utf-8-bom with dash

---

CHANGELOG.md

547c5f1 fix: utf-8-bom with dash (#177)
8fd941d build(deps): bump actions/setup-go from 4 to 5 (#175)
b573fe4 build(deps): bump golang.org/x/mod from 0.13.0 to 0.14.0 (#174)
2b5ef76 build(deps): bump github.com/google/go-cmp from 0.5.9 to 0.6.0 (#173)
03a0664 build(deps): bump golang.org/x/mod from 0.12.0 to 0.13.0 (#172)

prepare v2.6.1

---

CHANGELOG.md

a5a5d12 fix: Windows path overrides are broken (#184)
a73573b chore: bump golanci-lint from 1.54 to 1.56 (#182)
308412c build(deps): bump golang.org/x/mod from 0.15.0 to 0.16.0 (#183)
e00541f build(deps): bump golangci/golangci-lint-action from 3.7.0 to 4.0.0 (#180)
8774f2b build(deps): bump golang.org/x/mod from 0.14.0 to 0.15.0 (#179)

prepare v2.6.2
